# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/sebastian/Documents/Unreal Engine 5.4
GAMEPROJECTFILE =/media/sebastian/TOSHIBA EXT/MSI_Laptop/Overcooked_Unreal/OverCooked.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	OverCooked-Linux-DebugGame  \
	OverCooked-Linux-Shipping  \
	OverCooked \
	OverCookedEditor-Linux-DebugGame  \
	OverCookedEditor-Linux-Shipping  \
	OverCookedEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend OverCookedEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug OverCookedEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

OverCooked-Linux-DebugGame:
	 $(PROJECTBUILD) OverCooked Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

OverCooked-Linux-Shipping:
	 $(PROJECTBUILD) OverCooked Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

OverCooked:
	 $(PROJECTBUILD) OverCooked Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

OverCookedEditor-Linux-DebugGame:
	 $(PROJECTBUILD) OverCookedEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

OverCookedEditor-Linux-Shipping:
	 $(PROJECTBUILD) OverCookedEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

OverCookedEditor:
	 $(PROJECTBUILD) OverCookedEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
